language: nix
env:
  global:
    - GHC_VERSION=ghc802
    - secure: bLMthe7ioX7ie5I7Keq5brZ3JhAv7eWDbYAURvagqEBZbYa6h5dgMEPz24qXDiuWzm4K+lrU45fRx+i0iMsaDaxqHsc6wDN5WpAs5aOQTcmm1gW7JoXlvrUBh/NfOAMte0aGhgacTpOklnDqAY/YFRs3/Tp+AurqiPr/RAI58cbgB9EyaDyP4CrTF/ubMhZhyrQ3SgJWzHpGcKML0EGGxXyG7CUQC2sfj7l5X4wqLfxmNOzo4bkxWPxAPsUfUgBPDU51QRQ3V2554VALK+/LqTwcvX561Hll7w+HZ2yGJoI47VSnLw4vaHGBx7KbLPJxwmMCsy0o6NP2FtpmwP2MriRd1GwwMLwrajX8arnDYI6k34q6tnBgeGCcXiDxDfThKIVfqZ0Bd8bZMh1DP+JDTrGQGowMDTOKRZEa+p8fHC6Mg3tcpiHa5V+OxUXnbRnhls4Trz/pSfVM6jIxqPIE9cEirYytrT0tshlLCfRB+YnCNSN6Nr3iPBJrquTUBKqAppvtIQD2GXJR1MZpSDTwxd/cy64MlHnpz6hoPJCvlx/EuA74JPlagRMzGGKQxHC+Ug5y3NXH5vZpVfohgYcd6vTGAShaxrSNbAWnYVnrq5LjjoEaU1oJFYYxxWNz7C9a+MiNlXjvu1PAyEj5/UQ1sDtOHnbsJFyKsLG+vAfmx8o=

before_install:
  - >
      if ! echo "$TRAVIS_COMMIT_MESSAGE" \
         | grep -qvE  '\[(skip travis|travis skip)\]'
      then
        echo "[skip travis] has been found, exiting."
        exit
      fi

script:
  - nix-build default.nix --argstr compiler $GHC_VERSION
  - nix-env -iA nixpkgs.texlive.combined.scheme-full
  - result/bin/blog build

after_script:
  - bash publish.sh

#cache:
#  timeout: 300
#  directories:
#    - /nix
